### ISSUE TITLE
How to show several AR Sumerian scenes with tableview

### ISSUE THREAD

**Issue by CreateUp-Academy** [aws-samples/amazon-sumerian-arkit-starter-app#11]
I would like to show several AR Sumerian scenes with tableview in iOS App like following.
https://daddycoding.com/2017/10/17/ios-tutorials-triggering-tableviewcell-visit-site/

The sample cord shows only one scene.
https://github.com/aws-samples/amazon-sumerian-arkit-starter-app

Please let me know how to show several AR Sumerian scenes with tableview in iOS App.

**Comment by mike-starr** [comment]
Hi @CreateUp-Academy,

You should be able to do this by following the tutorial you linked, but in the last step - instead of using the ViewController class they provide - use the one in the Sumerian starter app (defined in ViewController.swift). You'll have to modify that class so that the scene URL can be passed in as a parameter instead of hard-coded - the tutorial you linked also has instructions on how to do that.
